name: build library

on: push

jobs:
  build-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup Rust toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y libclang-dev clang cmake wget ninja-build
          git clone https://github.com/rust-lang/rust.git -b beta
          wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-16/wasi-sdk-16.0-linux.tar.gz
          tar xvf wasi-sdk-16.0-linux.tar.gz
          echo "WASI_SDK_PATH=$(pwd)/wasi-sdk-16.0" >> "$GITHUB_ENV"
          cd rust
          git apply ../canonicalize.patch
          mkdir tmp
          cd tmp
          ../src/ci/docker/host-x86_64/dist-various-2/build-wasi-toolchain.sh
          cd ..
          ./configure --target=wasm32-wasi --disable-docs --set target.wasm32-wasi.wasi-root=/wasm32-wasi --enable-lld --tools=cargo
          ./x.py build --target x86_64-unknown-linux-gnu --target wasm32-wasi --stage 2
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y > /dev/null 2> /dev/null
          source $HOME/.cargo/env
          rustup toolchain link stage2 "$(pwd)/build/x86_64-unknown-linux-gnu/stage2"
          cargo --version
      - name: Build
        run: |
          source $HOME/.cargo/env
          export CC="${WASI_SDK_PATH}/bin/clang --sysroot=${WASI_SDK_PATH}/share/wasi-sysroot"
          cargo +stage2 build --target wasm32-wasi --release --features hterm

